SET SCHEMA FN71873@
--скрипт, в който са дефинирани функции и тестове с тях (поне две функции)

CREATE FUNCTION GET_CLINICS_N(V_CODE VARCHAR(10))
RETURNS VARCHAR(50)
RETURN
    SELECT NAME
    FROM CLINICS
    WHERE CODE = V_CODE@

VALUES FN71873.GET_CLINICS_N('10')@

SELECT NAME AS CNAME, FN71873.GET_CLINICS_N(CODE) AS CNAME
FROM CLINICS@

CREATE FUNCTION DOCTOR_INFORMATION(D_DCODE VARCHAR(10))
RETURNS TABLE(CNAME VARCHAR(50), DNAME VARCHAR(50), SPECIALIZATION VARCHAR(30))
RETURN
    SELECT C.NAME, D.NAME, SPECIALIZATION
    FROM CLINICS C, DOCTORS D
    WHERE C.CODE = D.CODE
    AND   D.CODE = D_DCODE@

SELECT *
FROM TABLE(FN71873.DOCTOR_INFORMATION(10)) T_TABLE@

