/* Relational Schemas
Clinics (code, name, compartmentCode)
Compartments (code, name, phoneNumber)
Registry staff (code, name, address, phoneNumber, compartmentCodes, compartmentPhones, patientName, patientEGN, patientBirthDate, patientFile)
Doctors (code, name, address, specialization, compartmentName, compartmentPhones)
Patients (EGN, name, birthDate, phoneNumber, file)
Discount Cards (code, dateOfIssue, validity, patientName, patientEGN, patientBirthDate)
Medication (code, name, expiryDate)
*/

SET SCHEMA FN71873;

DROP TABLE Clinics@
DROP TABLE Compartments@
DROP TABLE RegistryStaff@
DROP TABLE Doctors@
DROP TABLE Patients@
DROP TABLE DiscountCards@
DROP TABLE Medication@
DROP TABLE Doctors_Patients_Medication@

--Clinics (code, name)
CREATE TABLE Clinics (
    CODE VARCHAR(10) NOT NULL CONSTRAINT PK_CLINICS PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL
)@

--Compartments (name, phoneNumber, clinicCode)
CREATE TABLE Compartments (
    NAME VARCHAR(50) NOT NULL CONSTRAINT PK_COMPARTMENTS PRIMARY KEY,
    PHONENUMBER VARCHAR(10),
    CLINICCODE VARCHAR(10) NOT NULL FK_COMPARTMENTS_CLINICS REFERENCES CLINICS(CODE)
)@

--Registry staff (workNumber, name, address, phoneNumber, clinicCode)
CREATE TABLE RegistryStaff (
    WORKNUMBER VARCHAR(10) NOT NULL CONSTRAINT PK_REGISTRYSTAFF PRIMARY KEY,
    NAME VARCHAR(50),
    ADDRESS VARCHAR(200),
    PHONENUMBER VARCHAR(10),
    CLINICCODE VARCHAR(10) NOT NULL FK_REGISTRYSTAFF_CLINICS REFERENCES CLINICS(CODE)
)@

--Doctors (code, name, address, specialization, compartmentName, clinicCode)
CREATE TABLE Doctors (
    CODE VARCHAR(10) NOT NULL CONSTRAINT PK_DOCTORS PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    ADDRESS VARCHAR(200),
    SPECIALIZATION VARCHAR(30),
    COMPARTMENTNAME VARCHAR(50) NOT NULL FK_DOCTORS_COMPARTMENTS REFERENCES COMPARTMENTS(NAME),
    CLINICCODE VARCHAR(10) NOT NULL FK_DOCTORS_CLINICS REFERENCES CLINICS(CODE)
)@

ALTER TABLE DOCTORS
ADD SALARY DOUBLE@

--Patients (EGN, name, birthDate, phoneNumber, file)
CREATE TABLE Patients (
    EGN VARCHAR(10) NOT NULL CONSTRAINT PK_PATIENTS PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    BIRTHDATE DATE,
    PHONENUMBER VARCHAR(10),
    REGISTEREDNUMBER VARCHAR(10) NOT NULL FK_PATIENTS_REGISTRYSTAFF REFERENCES REGISTRYSTAFF(WORKNUMBER)
)@

--Discount Cards (code, dateOfIssue, validity, patientEGN, )
CREATE TABLE DiscountCards (
    CODE VARCHAR(10) NOT NULL CONSTRAINT PK_DISCOUNTCARDS PRIMARY KEY,
    DATEOFISSUE DATE NOT NULL,
    VALIDITY DATE,
    PATIENTEGN VARCHAR(10) NOT NULL FK_DISCOUNTCARDS_PATIENTS REFERENCES PATIENTS(EGN),
    REGISTRYSTAFFISSUED VARCHAR(50) NOT NULL FK_DISCOUNTCARDS_REGISTRYSTAFF REFERENCES REGISTRYSTAFF(WORKNUMBER)
)@

--Medication (code, name, expiryDate)
CREATE TABLE Medication (
    CODE VARCHAR(10) NOT NULL CONSTRAINT PK_MEDICATION PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    EXPIRITYDATE DATE NOT NULL
)@

--Doctors_Patients_Medication (code, codeDoctor, codeMedication, EGN, currentDate)
CREATE TABLE Doctors_Patients_Medication (
    CODE VARCHAR(10) NOT NULL CONSTRAINT PK_DOCTORS_PATIENTS_MEDICATION PRIMARY KEY,
    CODEDOCTOR VARCHAR(10) NOT NULL FK_DOCTORS_PATIENTS_MEDICATION_DOCTORS REFERENCES DOCTORS(CODE),
    CODEMEDICATION VARCHAR(10) NOT NULL FK_DOCTORS_PATIENTS_MEDICATION_MEDICATION REFERENCES MEDICATION(CODE),
    PATIENTEGN VARCHAR(10) NOT NULL FK_DOCTORS_PATIENTS_MEDICATION_PATIENTS REFERENCES PATIENTS(EGN),
    CURRENTDATE DATE
)@
